# Generated by Django 3.0.2 on 2020-01-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='real_name',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='editorial',
        ),
    ]
